import type { Metadata } from "next";
import { getServerToken } from "@/lib/get-server-token";
import { redirect } from "next/navigation";
import { getDecodedUser } from "@/lib/utils";
import { getUser } from "@/actions/auth/get-admin";
import { removeToken } from "@/lib/remove-token";

export const metadata: Metadata = {
  title: "FinalTry Innovations",
  description: "Generated by create next app",
};

// This is a server component by default since it's in a layout file
export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const token = getServerToken();

  if (!token) {
    return redirectToSignIn();
  }

  const user = getDecodedUser(token as string) as any;
  const serverUser = await getUser();

  if (!serverUser || user.id !== serverUser?.data?._id) {
    return redirectToSignIn();
  }

  return <div>{children}</div>;
}

// Helper function to redirect and handle token removal
async function redirectToSignIn() {
  removeToken(); // Ensure this function only runs in server-side context
  redirect("/sign-in");
}
